# Generated by Django 4.0.6 on 2022-08-02 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Contact',
                'ordering': ('-created',),
            },
        ),
    ]
