# Generated by Django 4.0.6 on 2022-07-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='About User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar/', verbose_name='User image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Day of birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
    ]
