# Generated by Django 4.0.6 on 2022-07-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, max_length=25, null=True, verbose_name='Phone number'),
        ),
    ]
