# Generated by Django 4.0.6 on 2022-08-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
    ]
