# Generated by Django 4.0.6 on 2022-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_from_user_message_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_readed',
            field=models.BooleanField(default=False),
        ),
    ]
