# Generated by Django 4.0.6 on 2022-09-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_is_readed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_readed',
        ),
    ]
